import { Complaint, AssignedTechnician, User, AppNotification } from './types';

export const CAMPUS_BUILDINGS = [
  'Science & Engineering Complex',
  'Main Academic Block',
  'Central Library',
  'Tech Park & Computing Labs',
  'Hostel Block A (North)',
  'Hostel Block B (South)',
  'Central Dining & Canteen',
  'Sports & Gymnasium Complex',
  'Mechanical Workshop Wing',
  'Biotechnology Research Lab',
];

export const COLLEGE_DEPARTMENTS = [
  'Computer Science & Engineering',
  'Electrical & Electronics Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Biotechnology',
  'Information Technology',
  'Business Administration',
  'Humanities & Sciences',
  'Campus Estate & Facility Staff',
];

export const TECHNICIANS: AssignedTechnician[] = [
  {
    id: 'TECH-01',
    name: 'Rajesh Kumar',
    department: 'Electrical Maintenance Division',
    phone: '+91 98451 22301',
    assignedAt: '2026-09-10T09:30:00Z',
    badge: 'Senior Electrician (Lic. #EL-491)',
  },
  {
    id: 'TECH-02',
    name: 'Marcus Brody',
    department: 'Plumbing & Water Supply Division',
    phone: '+91 98451 22302',
    assignedAt: '2026-09-10T11:15:00Z',
    badge: 'Master Plumber (Cert. #PL-102)',
  },
  {
    id: 'TECH-03',
    name: 'Sarah Jenkins',
    department: 'Campus Sanitation & Housekeeping',
    phone: '+91 98451 22303',
    assignedAt: '2026-09-09T14:20:00Z',
    badge: 'Housekeeping Lead Supervisor',
  },
  {
    id: 'TECH-04',
    name: 'David Chen',
    department: 'Campus IT & Networking Services',
    phone: '+91 98451 22304',
    assignedAt: '2026-09-11T08:00:00Z',
    badge: 'Senior Network Technician (Cisco CCNA)',
  },
  {
    id: 'TECH-05',
    name: 'Vikram Solanki',
    department: 'Carpentry & Estate Management',
    phone: '+91 98451 22305',
    assignedAt: '2026-09-08T10:00:00Z',
    badge: 'Estate Furniture Specialist',
  },
  {
    id: 'TECH-06',
    name: 'Elena Rostova',
    department: 'Scientific Laboratories Maintenance',
    phone: '+91 98451 22306',
    assignedAt: '2026-09-10T15:45:00Z',
    badge: 'Lab Equipment & Instrumentation Engineer',
  },
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-01',
    name: 'Aarav Sharma',
    collegeId: 'CS2023-4819',
    email: 'aarav.sharma@campus.edu',
    department: 'Computer Science & Engineering',
    role: 'student',
    phone: '+91 98112 34567',
    blockOrHostel: 'Hostel Block B (South)',
    roomNumber: 'Room 304',
    registeredAt: '2025-08-15T10:00:00Z',
    password: 'password123',
  },
  {
    id: 'user-02',
    name: 'Dr. Anita Roy',
    collegeId: 'FAC-MECH-102',
    email: 'anita.roy@campus.edu',
    department: 'Mechanical Engineering',
    role: 'staff',
    phone: '+91 98223 45678',
    blockOrHostel: 'Main Academic Block',
    roomNumber: 'Cabin 412',
    registeredAt: '2024-01-10T09:00:00Z',
    password: 'password123',
  },
  {
    id: 'user-03',
    name: 'Dean Arthur Vance',
    collegeId: 'ADMIN-ESTATE-01',
    email: 'estate.director@campus.edu',
    department: 'Campus Estate & Facility Staff',
    role: 'admin',
    phone: '+91 98334 56789',
    blockOrHostel: 'Estate & Maintenance Headquarters',
    roomNumber: 'Director Suite 101',
    registeredAt: '2023-06-01T08:30:00Z',
    password: 'adminpassword',
  },
];

export const SAMPLE_COMPLAINTS: Complaint[] = [
  {
    id: 'CMC-2026-1048',
    studentName: 'Aarav Sharma',
    collegeId: 'CS2023-4819',
    userRole: 'student',
    department: 'Computer Science & Engineering',
    email: 'aarav.sharma@campus.edu',
    location: 'Engineering Wing B, Room 204',
    building: 'Science & Engineering Complex',
    roomNumber: 'Room 204',
    category: 'Electrical',
    urgency: 'Medium',
    urgencyReason: 'Classroom ceiling fan non-functional causing heat distress during afternoon lectures.',
    rawDescription: 'fan not working in room 204 and switch is hot to touch',
    rewrittenComplaint:
      'Ceiling fan in Room 204 is completely non-operational, accompanied by an abnormal temperature rise on the wall switch. Please arrange immediate diagnostic inspection and component replacement.',
    summary: 'Ceiling fan & switch overheating in Room 204',
    suggestedDepartment: 'Electrical Maintenance Division',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    photoName: 'broken_fan_switch.jpg',
    status: 'In Progress',
    statusNotes: 'Technician on-site. Replacement capacitor and switchboard panel scheduled for installation.',
    assignedTechnician: TECHNICIANS[0],
    estimatedResolutionHours: 24,
    createdAt: '2026-09-10T08:15:00Z',
    updatedAt: '2026-09-11T02:30:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-10T08:15:00Z',
        actor: 'Aarav Sharma (Student)',
        note: 'Complaint submitted with AI analysis.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-10T09:30:00Z',
        actor: 'Admin Dispatcher',
        note: 'Assigned to Rajesh Kumar (Electrical Division).',
      },
      {
        status: 'In Progress',
        timestamp: '2026-09-10T14:00:00Z',
        actor: 'Rajesh Kumar',
        note: 'Inspected regulator circuit; procuring replacement wiring module from central store.',
      },
    ],
    safetyAction: 'Refrain from toggling the switchboard panel until technician inspection is complete.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1049',
    studentName: 'Priya Nair',
    collegeId: 'BT2022-7712',
    userRole: 'student',
    department: 'Biotechnology',
    email: 'priya.nair@campus.edu',
    location: 'Hostel Block B (South), 2nd Floor Restroom',
    building: 'Hostel Block B (South)',
    roomNumber: 'Restroom 2B',
    category: 'Plumbing',
    urgency: 'Emergency',
    urgencyReason: 'Active burst pipe with continuous water leakage threatening hallway flooding and electrical floor conduits.',
    rawDescription: 'water pipe leaking very fast flooding the 2nd floor bathroom in hostel B',
    rewrittenComplaint:
      'High-pressure main water pipe rupture reported in Hostel Block B 2nd floor washroom (2B). Significant flooding actively accumulating with risk of seepage into living corridors. Urgent shutoff and pipe replacement mandated.',
    summary: 'Severe main pipe rupture & flooding in Hostel B',
    suggestedDepartment: 'Plumbing & Water Supply Division',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    photoName: 'water_leak_restroom.jpg',
    status: 'In Progress',
    statusNotes: 'Main booster valve isolated. Pipe welding and drainage clearing underway.',
    assignedTechnician: TECHNICIANS[1],
    estimatedResolutionHours: 2,
    createdAt: '2026-09-11T01:45:00Z',
    updatedAt: '2026-09-11T02:50:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-11T01:45:00Z',
        actor: 'Priya Nair (Student)',
        note: 'Emergency complaint triggered via Campus AI Hotline.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-11T02:00:00Z',
        actor: 'Emergency Automated Router',
        note: 'Auto-dispatched to Marcus Brody (Emergency Plumbing Crew).',
      },
      {
        status: 'In Progress',
        timestamp: '2026-09-11T02:20:00Z',
        actor: 'Marcus Brody',
        note: 'Main line shutoff valve engaged. Drain vacuum deployed.',
      },
    ],
    safetyAction: 'Do not enter the flooded washroom area to prevent slipping and electrical contact.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1035',
    studentName: 'Rohan Mehta',
    collegeId: 'IT2024-3321',
    userRole: 'student',
    department: 'Information Technology',
    email: 'rohan.m@campus.edu',
    location: 'Central Library, 1st Floor Digital Study Wing',
    building: 'Central Library',
    roomNumber: 'Study Wing 105',
    category: 'Internet / Wi-Fi',
    urgency: 'High',
    urgencyReason: 'Access Point offline affecting 40+ students preparing for mid-term research submissions.',
    rawDescription: 'wifi not connecting in library first floor says authentication timeout',
    rewrittenComplaint:
      'Campus enterprise Wi-Fi SSID "Campus-Secure" is inaccessible across Central Library 1st Floor (Study Wing 105). Clients experiencing continuous RADIUS authentication timeouts and frequent packet drops. Network controller diagnosis required.',
    summary: 'Campus-Secure Wi-Fi AP outage in Central Library',
    suggestedDepartment: 'Campus IT & Networking Services',
    photoUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    photoName: 'wifi_ap_blinking.jpg',
    status: 'Resolved',
    statusNotes: 'Aruba AP-515 power-cycled; DHCP subnet pool lease refreshed. Signal verified at -52 dBm across the hall.',
    assignedTechnician: TECHNICIANS[3],
    estimatedResolutionHours: 4,
    createdAt: '2026-09-09T10:00:00Z',
    updatedAt: '2026-09-09T13:30:00Z',
    resolvedAt: '2026-09-09T13:30:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-09T10:00:00Z',
        actor: 'Rohan Mehta (Student)',
        note: 'Submitted via student portal.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-09T10:30:00Z',
        actor: 'IT Helpdesk Admin',
        note: 'Assigned to David Chen.',
      },
      {
        status: 'In Progress',
        timestamp: '2026-09-09T11:45:00Z',
        actor: 'David Chen',
        note: 'Identified IP address pool exhaustion on VLAN 40.',
      },
      {
        status: 'Resolved',
        timestamp: '2026-09-09T13:30:00Z',
        actor: 'David Chen',
        note: 'Subnet expanded and AP firmware restored.',
      },
    ],
    safetyAction: 'Connect to backup "Campus-Guest" portal while primary access is restored.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1042',
    studentName: 'Dr. Anita Roy',
    collegeId: 'FAC-MECH-102',
    userRole: 'staff',
    department: 'Mechanical Engineering',
    email: 'anita.roy@campus.edu',
    location: 'Main Academic Block, Lecture Hall 102',
    building: 'Main Academic Block',
    roomNumber: 'LH 102',
    category: 'Furniture',
    urgency: 'Low',
    urgencyReason: 'Unstable desk bench in 3rd row causing minor student disruption during lectures.',
    rawDescription: 'wooden desk row 3 wobbling badly screw loose could fall',
    rewrittenComplaint:
      'Lecture Hall 102, Row 3 wooden tiered desk unit has detached anchoring bolts and noticeable structural wobble. Carpentry reinforcement and bracket fastening requested prior to upcoming examination block.',
    summary: 'Loose bench fastening in Lecture Hall 102',
    suggestedDepartment: 'Carpentry & Estate Management',
    photoUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    photoName: 'loose_desk.jpg',
    status: 'Assigned',
    statusNotes: 'Work order dispatched to carpentry team for evening maintenance shift.',
    assignedTechnician: TECHNICIANS[4],
    estimatedResolutionHours: 36,
    createdAt: '2026-09-10T16:20:00Z',
    updatedAt: '2026-09-10T17:00:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-10T16:20:00Z',
        actor: 'Dr. Anita Roy (Staff)',
        note: 'Staff priority complaint logged.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-10T17:00:00Z',
        actor: 'Estate Dispatcher',
        note: 'Assigned to Vikram Solanki (Carpentry Team).',
      },
    ],
    safetyAction: 'Avoid placing heavy laptop bags on the end corner of Row 3 desk until fastened.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1038',
    studentName: 'Kunal Deshmukh',
    collegeId: 'ME2021-9904',
    userRole: 'student',
    department: 'Mechanical Engineering',
    email: 'kunal.d@campus.edu',
    location: 'Mechanical Workshop Wing, CNC Lab',
    building: 'Mechanical Workshop Wing',
    roomNumber: 'Lab 04',
    category: 'Laboratory',
    urgency: 'High',
    urgencyReason: 'Coolant circulation pump failure halting student capstone machine cutting projects.',
    rawDescription: 'cnc machine 2 coolant pump not circulating fluid burning smell',
    rewrittenComplaint:
      'CNC Milling Station #2 in the Mechanical Workshop Wing exhibits coolant circulation pump failure resulting in thermal overheating and smoke odor during spindle operation. Urgent electrical and hydraulic inspection required.',
    summary: 'Coolant pump motor failure on CNC Station #2',
    suggestedDepartment: 'Scientific Laboratories Maintenance',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    photoName: 'cnc_machine_lab.jpg',
    status: 'In Progress',
    statusNotes: 'Impeller assembly cleared; replacement seal ordered from OEM distributor.',
    assignedTechnician: TECHNICIANS[5],
    estimatedResolutionHours: 8,
    createdAt: '2026-09-10T11:00:00Z',
    updatedAt: '2026-09-10T16:30:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-10T11:00:00Z',
        actor: 'Kunal Deshmukh (Student)',
        note: 'Laboratory complaint registered.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-10T11:30:00Z',
        actor: 'Lab Superintendent',
        note: 'Assigned to Elena Rostova.',
      },
      {
        status: 'In Progress',
        timestamp: '2026-09-10T14:15:00Z',
        actor: 'Elena Rostova',
        note: 'Machine locked out with safety tag. Disassembled coolant housing.',
      },
    ],
    safetyAction: 'Do not power on CNC Station #2. Machine has been tagged Out of Service.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1029',
    studentName: 'Ananya Sen',
    collegeId: 'BA2023-1190',
    userRole: 'student',
    department: 'Business Administration',
    email: 'ananya.s@campus.edu',
    location: 'Central Dining & Canteen, South Entrance',
    building: 'Central Dining & Canteen',
    roomNumber: 'Ground Floor Entry',
    category: 'Cleaning',
    urgency: 'Medium',
    urgencyReason: 'Spilled beverage creating a slippery walking hazard during peak lunch hour.',
    rawDescription: 'huge food oil and drink spill near the canteen tray return area someone almost slipped',
    rewrittenComplaint:
      'Substantial liquid and beverage spill identified near the tray return station at Central Dining & Canteen South Entrance. Immediate sanitation, degreasing, and wet floor safety caution cones required.',
    summary: 'Slippery floor spill at Canteen Tray Return',
    suggestedDepartment: 'Campus Sanitation & Housekeeping',
    photoUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    photoName: 'cleaning_spill.jpg',
    status: 'Resolved',
    statusNotes: 'Sanitized with industrial degreaser; dry mopped and anti-slip mat deployed.',
    assignedTechnician: TECHNICIANS[2],
    estimatedResolutionHours: 2,
    createdAt: '2026-09-09T12:10:00Z',
    updatedAt: '2026-09-09T12:45:00Z',
    resolvedAt: '2026-09-09T12:45:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-09T12:10:00Z',
        actor: 'Ananya Sen (Student)',
        note: 'Submitted from mobile device.',
      },
      {
        status: 'Assigned',
        timestamp: '2026-09-09T12:15:00Z',
        actor: 'Canteen Facility Supervisor',
        note: 'Assigned to Sarah Jenkins.',
      },
      {
        status: 'Resolved',
        timestamp: '2026-09-09T12:45:00Z',
        actor: 'Sarah Jenkins',
        note: 'Spill completely mopped and hazard removed.',
      },
    ],
    safetyAction: 'Area cordoned off with caution cones until floor surface dried.',
    aiPowered: true,
  },
  {
    id: 'CMC-2026-1021',
    studentName: 'Prof. Mark Davis',
    collegeId: 'FAC-CS-88',
    userRole: 'staff',
    department: 'Computer Science & Engineering',
    email: 'mark.davis@campus.edu',
    location: 'Tech Park & Computing Labs, Lab 301',
    building: 'Tech Park & Computing Labs',
    roomNumber: 'Lab 301',
    category: 'Classroom',
    urgency: 'High',
    urgencyReason: 'Overhead ceiling laser projector not displaying HDMI input for senior design presentations.',
    rawDescription: 'projector keeps shutting down after 2 minutes in lab 301 red lamp blinking',
    rewrittenComplaint:
      'Ceiling-mounted Optoma laser projector in Computing Lab 301 experiences automatic thermal shutdown after 120 seconds of operation, displaying a flashing red lamp error indicator. Filter cleaning and lamp diagnostic required.',
    summary: 'Overheating projector shutdown in Lab 301',
    suggestedDepartment: 'Academic Facilities & AV Support',
    photoUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    photoName: 'projector_lamp_error.jpg',
    status: 'Closed',
    statusNotes: 'Replaced electrostatic dust filter and thermal sensor. Tested continuously for 45 minutes with no issues.',
    assignedTechnician: TECHNICIANS[0],
    estimatedResolutionHours: 6,
    createdAt: '2026-09-08T09:00:00Z',
    updatedAt: '2026-09-08T15:30:00Z',
    resolvedAt: '2026-09-08T15:00:00Z',
    timeline: [
      {
        status: 'Submitted',
        timestamp: '2026-09-08T09:00:00Z',
        actor: 'Prof. Mark Davis (Faculty)',
        note: 'Urgent teaching ticket created.',
      },
      {
        status: 'Resolved',
        timestamp: '2026-09-08T15:00:00Z',
        actor: 'AV Technical Specialist',
        note: 'Thermal sensor recalibrated and filter replaced.',
      },
      {
        status: 'Closed',
        timestamp: '2026-09-08T15:30:00Z',
        actor: 'Prof. Mark Davis',
        note: 'Faculty confirmed projector works satisfactorily.',
      },
    ],
    safetyAction: 'Do not attempt to open projector housing while power cable is attached.',
    aiPowered: true,
  },
];

export const SAMPLE_SAMPLE_PHOTOS = [
  {
    name: 'Broken Ceiling Fan',
    url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    category: 'Electrical',
    desc: 'Faulty motor and damaged blades',
  },
  {
    name: 'Water Pipe Leak',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    category: 'Plumbing',
    desc: 'Burst pipe dripping into basin',
  },
  {
    name: 'Damaged Desk & Chairs',
    url: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    category: 'Furniture',
    desc: 'Loose table leg and cracked seat',
  },
  {
    name: 'Wi-Fi AP Outage',
    url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    category: 'Internet / Wi-Fi',
    desc: 'Red LED blinking router',
  },
  {
    name: 'Sanitation Spill',
    url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    category: 'Cleaning',
    desc: 'Water spill on hallway tile',
  },
  {
    name: 'AV Projector Error',
    url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    category: 'Classroom',
    desc: 'Classroom ceiling projector unit',
  },
];

export const DEMO_STUDENT = DEMO_USERS[0];

export const SAMPLE_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    complaintId: 'CMC-2026-1049',
    title: 'Emergency Response Deployed',
    message: 'Technician Marcus Brody assigned to burst pipe flooding in Hostel Block B.',
    type: 'emergency',
    timestamp: '15 mins ago',
    read: false,
  },
  {
    id: 'notif-2',
    complaintId: 'CMC-2026-1048',
    title: 'Status Updated: In Progress',
    message: 'Rajesh Kumar has arrived at Science Complex Room 204 for fan diagnostic.',
    type: 'status_change',
    timestamp: '1 hour ago',
    read: false,
  },
  {
    id: 'notif-3',
    complaintId: 'CMC-2026-1035',
    title: 'Complaint Resolved',
    message: 'Wi-Fi AP in Central Library has been reconfigured and restored to full speed.',
    type: 'resolved',
    timestamp: 'Yesterday',
    read: true,
  },
];
